DELETE FROM sub_categories;
DELETE FROM order_line;
DELETE FROM orders;
DELETE FROM medicine;
DELETE FROM categories;
DELETE FROM users_roles;
DELETE FROM roles;
DELETE FROM user_urls;
DELETE FROM users;